### ISSUE TITLE
Some questions about :tailwind/config

### ISSUE THREAD

**Issue by kakinouchi** [teknql/shadow-cljs-tailwind-jit#2]
I'm sorry if I'm wrong to ask questions here.

I have two questions about setting `:tailwind/config`

1. Like https://tailwindcss.com/docs/theme#referencing-other-values, how can we write referencing other values in Clojure?
2. How can we write `require` notation? (e.g. to set `plugins: [require('@tailwindcss/ui')]`

Thank you.

**Comment by rschmukler** [comment]
I think the best way to do this will be to support using a `tailwind.config.js` for more advanced setups. Ultimately it may be worth adding support for custom syntax, but I think we're better off keeping it simple in the `:tailwind/config` and then leaving advanced usage to a true `tailwind.config.js` as suggested in #3

**Comment by kakinouchi** [comment]
That's true, I agree with you.
You can close this(#2) issue, thank you.
