### ISSUE TITLE
Refer to `tailwind.config.js`

### ISSUE THREAD

**Issue by kakinouchi** [teknql/shadow-cljs-tailwind-jit#3]
I have already tailwind.config.js file and run npm script to build tailwind css with other build tasks.

So I would like `shadow-cljs-tailwind-jit` to refer `tailwind.config.js` in my project instead of using `:tailwind/config`.

Thank you.

**Comment by kakinouchi** [comment]
@rschmukler @fnumatic 
Thank you for implementing to use Tailwind Config Files !

Let me ask another question.
In this usecase( https://github.com/teknql/shadow-cljs-tailwind-jit#using-with-tailwind-config-files ),
do we need postcss.config.js not only tailwind.config.js ?

I've gotten an error as below when trying to use tailwind config files:
```
You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
Error: Invalid mapping: {"generated":{"line":6,"column":-1},"source":"../../../src/tw/style.css","original":{"line":5,"column":30},"name":null}
...
```

Thank you.

**Comment by rschmukler** [comment]
In  the current implementation you will need both files - but PRs welcome if you'd like to change it!

**Comment by kakinouchi** [comment]
@rschmukler 
Sorry for the late reply.

I want to contribute to this project.

How do you usually test this project?
By creating a jar and loading the jar file in another project?

**Comment by rschmukler** [comment]
This is now possible with v1!
